services:
  safelinkdb:
    image: postgres:16
    container_name: safelink-db
    restart: always
    environment:
      POSTGRES_DB: safelink
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - safelinkdb:/var/lib/postgresql/data
  safelink:
    build:
      dockerfile: Dockerfile
    container_name: safelink-api
    depends_on:
      - safelinkdb
    restart: always
    environment:
      DATABASE_URL: jdbc:postgresql://safelinkdb:5432/safelink
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      PRIVATE_KEY: ${PRIVATE_KEY}
      PUBLIC_KEY: ${PUBLIC_KEY}
      API_KEY: ${API_KEY}
    ports:
      - "8080:8080"
volumes:
  safelinkdb: